// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "AkashicKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "AkashicKit", targets: [
            "AkashicCore", "AkashicStoreIO", "AkashicEntity", "AkashicZoteroImport",
            "AkashicExport", "AkashicIndex", "AkashicQuery", "AkashicGraph", "AkashicWoSImport",
        ]),
        .library(name: "AkashicAppKit", targets: ["AkashicAppKit"]),
        .executable(name: "akashic", targets: ["akashic"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jpsim/Yams.git", "5.0.0"..<"7.0.0"),
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.3.0"),
        .package(url: "https://github.com/modelcontextprotocol/swift-sdk.git", .upToNextMinor(from: "0.12.0")),
        .package(path: "repos/biblatex-apa-swift"),
    ],
    targets: [
        // #36：vendored libyaml（parser 面）。Yams 未把 CYaml 匯出成 product，
        // 而 event-level 解析是唯一剩下的防線方向。詳見 Sources/CLibYAML/include/VENDORED.md
        .target(name: "CLibYAML",
                path: "Sources/CLibYAML",
                sources: ["src"],
                publicHeadersPath: "include",
                // **符號前綴**：Yams 的 CYaml 已在同一個 process 裡，不隔離會 duplicate
                // symbol。用 -D 重命名而非改原始碼——原始碼保持與上游逐字相同，更新時
                // 直接 cp 覆蓋即可（見 include/VENDORED.md）。
                cSettings: [
                    .define("MAX_NESTING_LEVEL", to: "AKYAML_MAX_NESTING_LEVEL"),
                    .define("yaml_alias_event_initialize", to: "akyaml_alias_event_initialize"),
                    .define("yaml_document_add_mapping", to: "akyaml_document_add_mapping"),
                    .define("yaml_document_add_scalar", to: "akyaml_document_add_scalar"),
                    .define("yaml_document_add_sequence", to: "akyaml_document_add_sequence"),
                    .define("yaml_document_append_mapping_pair", to: "akyaml_document_append_mapping_pair"),
                    .define("yaml_document_append_sequence_item", to: "akyaml_document_append_sequence_item"),
                    .define("yaml_document_delete", to: "akyaml_document_delete"),
                    .define("yaml_document_end_event_initialize", to: "akyaml_document_end_event_initialize"),
                    .define("yaml_document_get_node", to: "akyaml_document_get_node"),
                    .define("yaml_document_get_root_node", to: "akyaml_document_get_root_node"),
                    .define("yaml_document_initialize", to: "akyaml_document_initialize"),
                    .define("yaml_document_start_event_initialize", to: "akyaml_document_start_event_initialize"),
                    .define("yaml_emitter_close", to: "akyaml_emitter_close"),
                    .define("yaml_emitter_delete", to: "akyaml_emitter_delete"),
                    .define("yaml_emitter_dump", to: "akyaml_emitter_dump"),
                    .define("yaml_emitter_emit", to: "akyaml_emitter_emit"),
                    .define("yaml_emitter_flush", to: "akyaml_emitter_flush"),
                    .define("yaml_emitter_initialize", to: "akyaml_emitter_initialize"),
                    .define("yaml_emitter_open", to: "akyaml_emitter_open"),
                    .define("yaml_emitter_set_break", to: "akyaml_emitter_set_break"),
                    .define("yaml_emitter_set_canonical", to: "akyaml_emitter_set_canonical"),
                    .define("yaml_emitter_set_encoding", to: "akyaml_emitter_set_encoding"),
                    .define("yaml_emitter_set_indent", to: "akyaml_emitter_set_indent"),
                    .define("yaml_emitter_set_output", to: "akyaml_emitter_set_output"),
                    .define("yaml_emitter_set_output_file", to: "akyaml_emitter_set_output_file"),
                    .define("yaml_emitter_set_output_string", to: "akyaml_emitter_set_output_string"),
                    .define("yaml_emitter_set_unicode", to: "akyaml_emitter_set_unicode"),
                    .define("yaml_emitter_set_width", to: "akyaml_emitter_set_width"),
                    .define("yaml_event_delete", to: "akyaml_event_delete"),
                    .define("yaml_free", to: "akyaml_free"),
                    .define("yaml_get_version", to: "akyaml_get_version"),
                    .define("yaml_get_version_string", to: "akyaml_get_version_string"),
                    .define("yaml_malloc", to: "akyaml_malloc"),
                    .define("yaml_mapping_end_event_initialize", to: "akyaml_mapping_end_event_initialize"),
                    .define("yaml_mapping_start_event_initialize", to: "akyaml_mapping_start_event_initialize"),
                    .define("yaml_parser_delete", to: "akyaml_parser_delete"),
                    .define("yaml_parser_fetch_more_tokens", to: "akyaml_parser_fetch_more_tokens"),
                    .define("yaml_parser_initialize", to: "akyaml_parser_initialize"),
                    .define("yaml_parser_load", to: "akyaml_parser_load"),
                    .define("yaml_parser_parse", to: "akyaml_parser_parse"),
                    .define("yaml_parser_scan", to: "akyaml_parser_scan"),
                    .define("yaml_parser_set_encoding", to: "akyaml_parser_set_encoding"),
                    .define("yaml_parser_set_input", to: "akyaml_parser_set_input"),
                    .define("yaml_parser_set_input_file", to: "akyaml_parser_set_input_file"),
                    .define("yaml_parser_set_input_string", to: "akyaml_parser_set_input_string"),
                    .define("yaml_parser_update_buffer", to: "akyaml_parser_update_buffer"),
                    .define("yaml_queue_extend", to: "akyaml_queue_extend"),
                    .define("yaml_read_handler_t", to: "akyaml_read_handler_t"),
                    .define("yaml_realloc", to: "akyaml_realloc"),
                    .define("yaml_scalar_event_initialize", to: "akyaml_scalar_event_initialize"),
                    .define("yaml_sequence_end_event_initialize", to: "akyaml_sequence_end_event_initialize"),
                    .define("yaml_sequence_start_event_initialize", to: "akyaml_sequence_start_event_initialize"),
                    .define("yaml_set_max_nest_level", to: "akyaml_set_max_nest_level"),
                    .define("yaml_stack_extend", to: "akyaml_stack_extend"),
                    .define("yaml_strdup", to: "akyaml_strdup"),
                    .define("yaml_stream_end_event_initialize", to: "akyaml_stream_end_event_initialize"),
                    .define("yaml_stream_start_event_initialize", to: "akyaml_stream_start_event_initialize"),
                    .define("yaml_string_extend", to: "akyaml_string_extend"),
                    .define("yaml_string_join", to: "akyaml_string_join"),
                    .define("yaml_token_delete", to: "akyaml_token_delete"),
                    .define("yaml_write_handler_t", to: "akyaml_write_handler_t")
                ]),
        .target(name: "AkashicCore", dependencies: ["CLibYAML",
            .product(name: "Yams", package: "Yams"),
        ]),
        .target(name: "AkashicStoreIO", dependencies: [
            "AkashicCore",
            .product(name: "Yams", package: "Yams"),
        ]),
        .target(name: "AkashicEntity", dependencies: ["AkashicCore"]),
        .target(name: "AkashicSQLite"),
        .target(name: "AkashicZoteroImport", dependencies: ["AkashicStoreIO", "AkashicSQLite"]),
        .target(name: "AkashicIndex", dependencies: ["AkashicStoreIO", "AkashicSQLite"]),
        .target(name: "AkashicQuery", dependencies: ["AkashicIndex", "AkashicSQLite"]),
        .target(name: "AkashicGraph", dependencies: ["AkashicIndex", "AkashicSQLite"]),
        .target(name: "AkashicWoSImport", dependencies: ["AkashicCore", "AkashicStoreIO"]),
        .target(name: "AkashicExport", dependencies: [
            "AkashicStoreIO",
            .product(name: "BiblatexAPA", package: "biblatex-apa-swift"),
        ]),
        .executableTarget(name: "akashic", dependencies: [
            "AkashicCore", "AkashicStoreIO", "AkashicEntity", "AkashicZoteroImport",
            "AkashicWoSImport",
            "AkashicExport", "AkashicIndex", "AkashicQuery", "AkashicGraph",
            .product(name: "ArgumentParser", package: "swift-argument-parser"),
        ]),
        .target(name: "AkashicAppKit", dependencies: [
            "AkashicCore", "AkashicStoreIO", "AkashicEntity", "AkashicZoteroImport",
            "AkashicExport", "AkashicIndex", "AkashicQuery", "AkashicGraph",
        ]),
        .target(name: "AkashicMCPKit", dependencies: [
            "AkashicCore", "AkashicStoreIO", "AkashicEntity", "AkashicZoteroImport",
            "AkashicExport", "AkashicIndex", "AkashicQuery", "AkashicGraph",
            .product(name: "Yams", package: "Yams"),
        ]),
        .executableTarget(name: "akashic-mcp", dependencies: [
            "AkashicMCPKit",
            .product(name: "MCP", package: "swift-sdk"),
        ]),
        .testTarget(name: "AkashicKitTests", dependencies: [
            "AkashicCore", "AkashicStoreIO", "AkashicEntity", "AkashicZoteroImport",
            "AkashicExport", "AkashicIndex", "AkashicQuery", "AkashicGraph", "AkashicSQLite",
            "AkashicWoSImport",
        ]),
        .testTarget(name: "AkashicCLITests", dependencies: ["akashic"]),
        .testTarget(name: "AkashicMCPTests", dependencies: ["AkashicMCPKit", "akashic-mcp"]),
        .testTarget(name: "AkashicAppKitTests",
                    dependencies: ["AkashicAppKit", "AkashicCore", "AkashicStoreIO"]),
    ]
)
